In [1]:
import numpy as np
vector = np.random.randint(1, 21, size=15)
print("Original vector:\n", vector)

Original vector:
 [ 5 18 15 18 19  6  6  7  9  4  2 10  8 19 20]


In [2]:
reshaped = vector.reshape(3, 5)
print("Reshaped (3x5):\n", reshaped)

Reshaped (3x5):
 [[ 5 18 15 18 19]
 [ 6  6  7  9  4]
 [ 2 10  8 19 20]]


In [3]:
for row in reshaped:
    row[row.argmax()] = 0
print("After replacing max in each row with 0:\n", reshaped)

print("Shape of array:", reshaped.shape)

After replacing max in each row with 0:
 [[ 5 18 15 18  0]
 [ 6  6  7  0  4]
 [ 2 10  8 19  0]]
Shape of array: (3, 5)


In [4]:
arr = np.array([[9, 8, 4], [8, 3, 4], [2, 5, 8], [8, 0, 1]], dtype=np.int32)
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

Array:
 [[9 8 4]
 [8 3 4]
 [2 5 8]
 [8 0 1]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [5]:
matrix = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [6]:
array = np.array([[0, 1, 2], [3, 4, 5]])
diagonal_sum = np.trace(array)
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [7]:
original = np.array([[1, 2], [3, 4], [5, 6]])
reshaped = original.reshape(2, 3)
print("Original (3x2):\n", original)
print("Reshaped (2x3):\n", reshaped)


Original (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
